server:
  port: 80
spring:
  application:
    name: server
  profiles:
    active: dev
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: true
logging:
  level:
    io.github.lumklar.server: debug
  file:
    path: ./logs
  charset:
    console: UTF-8
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
