name: Cleanup Old Docker Images
on:
  schedule:
    - cron: "0 3 * * *"  # 每天凌晨3点运行
  workflow_dispatch:     # 支持手动触发

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # ------------------------------------------------------------
      # 1. 删除老旧的dev docker镜像
      # TODO 使用配置文件统一配置
      # ------------------------------------------------------------
      - name: Cleanup Dev Docker Images
        uses: snok/container-retention-policy@v2
        with:
          image-names: sortrss  # 你的镜像名
          cut-off:  A week ago UTC    # 删除超过1周的
          keep-at-least: 10           # 但至少保留10个最新版本
          filter-tags: "dev-*"        # 只处理 dev- 开头的标签
          account-type: personal      # 个人或 org
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
      # ------------------------------------------------------------
      # 2. 删除所有悬空镜像
      # ------------------------------------------------------------
      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: sortrss
          keep-n-untagged: 5
